/*
 * modprog1, 2018a
 * Ex #3c a program that generates a random number in a range of user choice,
 * and user have to guess the generated number.
 * Written by: qussay firon
 * id: 327601779
 * login: kuchipe
 *
 * usage example
 * input: 10 5 4 6 8 7 0
 * output:
 * too small
 * too small
 * 3 3
 * 100
 * again? 1:YES
 */
#include <iostream>
#include <cstdlib>
#include <time.h>

using std::cout;
using std::cin;
using std::endl;
/*                                     Main                                  */
int main() {

  unsigned int x, //The number user enters
         random, //A random number generated by the computer
         guess, // A number the computer tries to guess
         difference, // A number need for the rational user guess
         tries, // The tries number of the real user
         rationalUser, // The tries number of the rational user
         grade; // ratio of rational user tries on normal user tries
  srand(1); // Needed for generating random numbers
  do {
    cin >> x; // Taking values from the user
    tries = 0; // Setting real user tries to 0
    rationalUser = 1; // Setting rational user tries to 1
    random = rand() % (x+1); // Generating a random number
    guess = (x % 2 == 0) ? (x/2) : ((x/2) + 1); // Calculating the first
    // guess value
    difference = (guess % 2 == 0) ? (guess/2) : (guess/2)+1; // Calculating
    // the first difference value if guess is even then
    //difference=guess/2 if guess is odd then then difference=(guess/2)+1

    while (guess != random) {// Calculating the rational user tries number.
      if (guess < random) {// if the guess is smaller than random we add
        // the difference to sum
        guess += difference;
      } else if (guess > random){// if the guess is bigger than the
        //random we subtract difference from the guess
        guess -= difference;
      }
      difference =  //Diving difference on 2 to make the algorithm true
          (difference % 2 == 0) ? (difference/2) : (difference/2)+1;
      rationalUser++; // Add one to rational user tries
    }

    //The numbers of user guessing
    do {
      cin >> x; //Taking values from user
      if (x < random) //Checks if the guess is less than the random
        cout << "too small" << endl;
      else if (x > random)//Checks if the guess is bigger than the random
        cout << "too big" << endl;
      tries++;
    } while (x != random);

    cout << tries << " " << rationalUser << endl;
    grade = (int)(((double)rationalUser/tries)*100); //Calculating grade
    cout << ((grade > 100) ? 100 : grade) << endl; //printing grade
    cout << "again? 1:YES" << endl;
    cin >> x;
  } while (x == 1); // if x equals to 1 repeat game
  return EXIT_SUCCESS;
}

